from pydantic import BaseModel, Field
from typing import List, Optional

class IngestRequest(BaseModel):
    """
    Request model for ingesting book content.
    """
    book_id: str = Field(..., description="Unique identifier for the book.")
    content: str = Field(..., description="Content of the book in Markdown or HTML format.")
    content_type: str = Field(..., description="Type of content: 'markdown' or 'html'.")

class ChatRequest(BaseModel):
    """
    Request model for the chat endpoint.
    """
    question: str = Field(..., description="The user's question.")
    selected_text: Optional[str] = Field(None, description="Optional selected text from the document for focused QA.")

class ChatResponse(BaseModel):
    """
    Response model for the chat endpoint.
    """
    answer: str = Field(..., description="The answer generated by the LLM.")
    sources: List[str] = Field(..., description="List of unique book IDs from which chunks were retrieved.")
